Check for more errors from oc exec

diff --git a/clusterbuster b/clusterbuster
--- a/clusterbuster
+++ b/clusterbuster
@@ -1114,7 +1114,7 @@ function create_sync_service_if_needed() {
 function get_pod_timestamp() {
     local format=${1:-%s.%N}
     shift
-    _OC exec "$@" -- /bin/sh -c "date '+$format'"
+    _OC exec "$@" -- /bin/sh -c "date '+$format'" || killthemall "Unable to retrieve timestamp from pod $*"
 }
 
 function get_prometheus_pod_timestamp() {
@@ -1152,7 +1152,7 @@ function get_pod_and_local_timestamps() {
     local remote_ts
     local second_local_ts
     first_local_ts=$(date +%s.%N)
-    remote_ts=$(__OC exec "$@" -- /bin/sh -c "date +%s.%N" </dev/null)
+    remote_ts=$(__OC exec "$@" -- /bin/sh -c "date +%s.%N" </dev/null) || killthemall "Unable to retrieve sync pod timestamp"
     second_local_ts=$(date +%s.%N)
     _OC exec --stdin=true "$@" -- /bin/sh -c "cat > '$controller_timestamp_file'" <<EOF
 {
@@ -1197,8 +1197,11 @@ function retrieve_prometheus_snapshot() {
     local promdb_name
     promdb_name="promdb_$(readable_timestamp "$prometheus_starting_timestamp")_$(readable_timestamp "$prometheus_ending_timestamp")"
     local promdb_path="${dir:+${dir}/}${promdb_name}.tar"
-    __OC exec -n openshift-monitoring prometheus-k8s-0 -c prometheus -- /bin/sh -c "tar cf - . -C /prometheus --transform 's,^[.],./${promdb_name},' .; true" > "$promdb_path"
-    echo "Prometheus snapshot retrieved" | echo_if_desired 1>&2
+    if __OC exec -n openshift-monitoring prometheus-k8s-0 -c prometheus -- /bin/sh -c "tar cf - . -C /prometheus --transform 's,^[.],./${promdb_name},' .; true" > "$promdb_path" ; then
+	echo "Prometheus snapshot retrieved" | echo_if_desired 1>&2
+    else
+	echo "Unable to retrieve Prometheus snapshot"
+    fi
 }
 
 function ts() {
