- Support Azure - Restrict masters to 1 or 3 - Allow 0 workers - Move platform validation earlier so work doesn't get done prior to validation. - Don't generate ssh key by default; use user's or value of -k - Fix comments, indentation, shellcheck

diff --git a/oinst b/oinst
--- a/oinst
+++ b/oinst
@@ -120,7 +120,7 @@ declare -i do_override=0
 declare -i download_oc=0
 declare -i force_local_tools=0
 declare -i force_postinstall=0
-declare -i generate_cluster_key=1
+declare -i generate_cluster_key=0
 declare -i generate_manifest=0
 declare -i install_stage=0
 declare -i login_succeeded=0
@@ -188,9 +188,11 @@ $(do_platforms platform_help install_types | indent 7)
                             KEY: clean_install_cache (default=0)
        -d install_dir       Use the specified dir as working directory and
                             cluster name.  Default is ${LOGNAME:-}-<platform>.
-       -k/-K                Generate ssh key for the cluster.  If not set,
-                            use user's standard ssh key.
-                            KEY: generate_cluster_key (default=1)
+       -k pubkey_file       Use the specified public key file for the cluster.
+                            Default $pubkey_file
+       -K                   Generate ssh key for the cluster.  If not set,
+                            use user's standard ssh key or value of -k
+                            KEY: generate_cluster_key (default=0)
        -l/-L                Don't clean up on exit.  You can exit with status
                             77 for no cleanup or 88 to force cleanup.
                             KEY: do_cleanup (default=1)
@@ -273,7 +275,7 @@ $(do_platforms platform_help default_domain | indent -28)
         kubechart_port      Use the specified port for kubechart.  oschart
                             runs at port+1.  Implies -b.  Default is ${default_kubechart_port}.
         pubkey_file         Specify the path to the desired public key
-                            Default $pubkey_file
+                            Equivalent to -k.  Default $pubkey_file
         pull_secret         Specify the path to the pull secret.
                             Default $pull_secret
         rebuild             Always rebuild the installer, when using local
@@ -358,14 +360,25 @@ function indent() {
 function cmdline_replicas() {
     local node_type=$1
     local default=$2
-    local actual=0
     case "$node_type" in
-	master) actual=$master_count ;;
-	worker) actual=$worker_count ;;
-	*)                           ;;
+	master)
+	    case "$master_count" in
+		1|3) echo "$master_count" ;;
+		0)   echo "$default"      ;;
+		*)
+		    fatal "Unspported number of masters (should be 1 or 3)"
+		    ;;
+	    esac
+	    return
+	    ;;
+	worker)
+	    (( worker_count < 0 )) && worker_count=0
+	    echo "$worker_count"
+	    return
+	    ;;
+	*)  ;;
     esac
-    (( actual == 0 )) && actual=$default
-    echo "$actual"
+    echo "$default"
 }
 
 function run_installer() {
@@ -924,7 +937,6 @@ function validate_environment() {
 	local g=${f//./\\.}
 	grep -q "$g" "$pull_secret" || warn "No secret for '$f' in pull secret $pull_secret; expect installation to fail"
     done
-    platform_dispatch validate
 }
 
 function confirm_install() {
@@ -1289,7 +1301,7 @@ function register_options() {
 }
 
 function process_options() {
-    while getopts ":AaBbCcd:HhKkLln:Oop:qUuV:vX:x:Yy-:" opt ; do
+    while getopts ":AaBbCcd:HhKk:Lln:Oop:qUuV:vX:x:Yy-:" opt ; do
 	case "$opt" in
 	    A) all_releases=0		    ;;
 	    a) all_releases=1		    ;;
@@ -1298,8 +1310,9 @@ function process_options() {
 	    C) clean_install_cache=0	    ;;
 	    c) clean_install_cache=1	    ;;
 	    d) install_dir="$OPTARG"        ;;
-	    K) generate_cluster_key=0	    ;;
-	    k) generate_cluster_key=1	    ;;
+	    K) generate_cluster_key=1	    ;;
+	    k) pubkey_file="$OPTARG"
+	       generate_cluster_key=0       ;;
 	    L) do_cleanup=1		    ;;
 	    l) do_cleanup=0		    ;;
 	    n) release_channel="$OPTARG"    ;;
@@ -1486,6 +1499,8 @@ worker_type=${worker_type:-$platform_type}
 [[ -n $OPENSHIFT_INSTALL_PLATFORM ]] || help
 
 export OPENSHIFT_INSTALL_PLATFORM
+platform_dispatch validate ||
+    fatal "Cannot validate platform configuration"
 platform_dispatch setup "$install_type"
 
 OPENSHIFT_INSTALL_BASE_DOMAIN=$(platform_dispatch base_domain)
@@ -1518,7 +1533,7 @@ mkdir -p "$install_dir" || fatal "Can't create installation directory $install_d
 if (( generate_cluster_key )) ; then
     OPENSHIFT_INSTALL_SSH_KEY=$(realpath "$install_dir/cluster")
     echo "Generating cluster key..."
-    ssh-keygen -f "$OPENSHIFT_INSTALL_SSH_KEY" -N '' || {
+    ssh-keygen -f "$OPENSHIFT_INSTALL_SSH_KEY" -N '' -q || {
 	echo "Can't create cluster key"
 	rm -rf "$install_dir"
 	exit 1
