Check that platform modules have not polluted the namespace

diff --git a/oinst b/oinst
--- a/oinst
+++ b/oinst
@@ -46,6 +46,107 @@ if [[ -z ${___topsc:-} ]] ; then
     [[ -z $___topdir ]] && fatal "Can't find directory for $0"
 fi
 
+function clean_startup() {
+    [[ -f $___realsc ]] && rm -f "$___realsc"
+}
+
+# This allows us to edit the script while another instance is running
+# since this script sticks around until the user exits the spawned shell.
+# It's fine for the running script to be removed, since the shell still
+# has its open file descriptor.
+if [[ $# = 0 || $1 != "--DoIt=$0" ]] ; then
+    tmpsc=$(mktemp)
+    [[ -z $tmpsc || ! -f $tmpsc || -L $tmpsc ]] && fatal "Can't create temporary script file"
+    trap clean_startup EXIT SIGHUP SIGINT SIGQUIT SIGTERM
+    PATH+=${PATH:+:}$___topdir
+    cat "$0" > "$tmpsc"
+    chmod +x "$tmpsc"
+    exec "$tmpsc" "--DoIt=$tmpsc" "$@"
+else
+    ___realsc=${1#--DoIt=}
+    clean_startup
+    shift
+fi
+
+# Globals
+declare -A release_base_map=()
+release_base_map[origin-release]='4.2.0-0.okd'
+release_base_map[openshift-release]='4-stable'
+
+declare -A subdir_map=()
+subdir_map[origin-release]='origin'
+subdir_map[openshift-release]='ocp'
+
+declare -r kubechart=${KUBECHART:-$GOPATH/src/github.com/sjenning/kubechart/kubechart}
+declare -r oschart=${OSCHART:-$GOPATH/src/github.com/sjenning/oschart/oschart}
+declare -r default_repo_base=openshift-release
+
+declare -A global_platforms=()
+
+declare -A global_diagnostics=()
+
+declare install_type=
+declare install_domain=${OPENSHIFT_INSTALL_DOMAIN:-}
+declare install_dir=${OPENSHIFT_INSTALL_DIR:-$install_domain}
+declare install_version=latest_default
+declare pull_secret=${OPENSHIFT_INSTALL_PULL_SECRET_PATH:-$HOME/Downloads/pull-secret}
+declare pubkey_file=${OPENSHIFT_INSTALL_SSH_PUB_KEY_PATH:-$HOME/.ssh/id_rsa.pub}
+declare srcdir=${GOPATH:-$HOME/go}/src/github.com/openshift/installer
+declare install=$srcdir/bin/openshift-install
+declare release_channel=
+declare repo=$default_repo_base
+declare _____current_platform
+
+# shellcheck disable=SC2155
+declare -r OC=$(type -p oc)
+[[ -z $OC ]] && fatal "Can't find oc command"
+# shellcheck disable=SC2155
+declare -r JQ=$(type -p jq)
+[[ -z $JQ ]] && fatal "Can't find jq command"
+# shellcheck disable=SC2155
+declare -r owd=$(pwd)
+declare -i clean_install_cache=0
+declare -i clean_shutdown=0
+declare -i cleanup_run=0
+declare -i created_kubechart=0
+declare -i created_oschart=0
+declare -i do_cleanup=1
+declare -i do_login=1
+declare -i do_override=0
+declare -i force_local_tools=0
+declare -i force_postinstall=0
+declare -i install_stage=0
+declare -i login_succeeded=0
+declare -i master_count=0
+declare -i noconfirm=0
+declare -i overwrite=0
+declare -i query=0
+declare -i rebuild=0
+declare -i run_kubechart=0
+declare -i run_oschart=0
+declare -i wait_for_complete=1
+declare -i worker_count=0
+declare -i host_prefix_bits=23
+declare api_version=v1
+declare cleanup_only_dir=
+declare config_file=
+declare console_route=
+declare ext_installer=
+declare -r -i default_kubechart_port=3000
+declare kubechart_port=
+declare loglevel=
+declare oschart_port=
+declare release_source=
+declare run_command=
+declare masterconffile=
+declare masterconfdata=
+declare workerconffile=
+declare workerconfdata=
+declare platformconffile=
+declare platformconfdata=
+declare -a options_to_process=()
+declare -A option_registrations=()
+
 function print_help() {
     cat <<EOF
 Usage: $___topsc [options] [install_type]
@@ -143,116 +244,6 @@ EOF
     exit 1
 }
 
-function clean_startup() {
-    [[ -f $___realsc ]] && rm -f "$___realsc"
-}
-
-# This allows us to edit the script while another instance is running
-# since this script sticks around until the user exits the spawned shell.
-# It's fine for the running script to be removed, since the shell still
-# has its open file descriptor.
-if [[ $# = 0 || $1 != "--DoIt=$0" ]] ; then
-    tmpsc=$(mktemp)
-    [[ -z $tmpsc || ! -f $tmpsc || -L $tmpsc ]] && fatal "Can't create temporary script file"
-    trap clean_startup EXIT SIGHUP SIGINT SIGQUIT SIGTERM
-    PATH+=${PATH:+:}$___topdir
-    cat "$0" > "$tmpsc"
-    chmod +x "$tmpsc"
-    exec "$tmpsc" "--DoIt=$tmpsc" "$@"
-else
-    ___realsc=${1#--DoIt=}
-    clean_startup
-    shift
-fi
-
-# Globals
-declare -A release_base_map=()
-release_base_map[origin-release]='4.2.0-0.okd'
-release_base_map[openshift-release]='4-stable'
-
-declare -A subdir_map=()
-subdir_map[origin-release]='origin'
-subdir_map[openshift-release]='ocp'
-
-declare -r kubechart=${KUBECHART:-$GOPATH/src/github.com/sjenning/kubechart/kubechart}
-declare -r oschart=${OSCHART:-$GOPATH/src/github.com/sjenning/oschart/oschart}
-declare -r default_repo_base=openshift-release
-
-declare -A global_platforms=()
-
-declare -A global_diagnostics=()
-
-declare install_type=
-declare install_domain=${OPENSHIFT_INSTALL_DOMAIN:-}
-declare install_dir=${OPENSHIFT_INSTALL_DIR:-$install_domain}
-declare install_version=latest_default
-declare pull_secret=${OPENSHIFT_INSTALL_PULL_SECRET_PATH:-$HOME/Downloads/pull-secret}
-declare pubkey_file=${OPENSHIFT_INSTALL_SSH_PUB_KEY_PATH:-$HOME/.ssh/id_rsa.pub}
-declare srcdir=${GOPATH:-$HOME/go}/src/github.com/openshift/installer
-declare install=$srcdir/bin/openshift-install
-declare release_channel=
-declare repo=$default_repo_base
-declare -a platform_path=
-
-# shellcheck disable=SC2155
-declare -r OC=$(type -p oc)
-[[ -z $OC ]] && fatal "Can't find oc command"
-# shellcheck disable=SC2155
-declare -r JQ=$(type -p jq)
-[[ -z $JQ ]] && fatal "Can't find jq command"
-# shellcheck disable=SC2155
-declare -r owd=$(pwd)
-declare -i clean_install_cache=0
-declare -i clean_shutdown=0
-declare -i cleanup_run=0
-declare -i created_kubechart=0
-declare -i created_oschart=0
-declare -i do_cleanup=1
-declare -i do_login=1
-declare -i do_override=0
-declare -i force_local_tools=0
-declare -i force_postinstall=0
-declare -i install_stage=0
-declare -i login_succeeded=0
-declare -i master_count=0
-declare -i noconfirm=0
-declare -i overwrite=0
-declare -i query=0
-declare -i rebuild=0
-declare -i run_kubechart=0
-declare -i run_oschart=0
-declare -i wait_for_complete=1
-declare -i worker_count=0
-declare -i host_prefix_bits=23
-declare api_version=v1
-declare cleanup_only_dir=
-declare config_file=
-declare console_route=
-declare ext_installer=
-declare -r -i default_kubechart_port=3000
-declare kubechart_port=
-declare loglevel=
-declare oschart_port=
-declare release_source=
-declare run_command=
-declare masterconffile=
-declare masterconfdata=
-declare workerconffile=
-declare workerconfdata=
-declare platformconffile=
-declare platformconfdata=
-declare -a options_to_process=()
-declare -A option_registrations=()
-
-# Running nested installs is liable to be problematic
-if [[ -n ${OPENSHIFT_INSTALL_INTERLOCK:-} ]] ; then
-    if [[ ${1:-} = -h* ]] ; then
-	echo "Already in ${___topsc:-oinst} environment!"
-	help
-    fi
-    fatal "Already in ${___topsc:-oinst} environment"
-fi
-
 ################################################################
 ### Utilities						     ###
 ################################################################
@@ -347,14 +338,15 @@ function do_create_bastion() {
 }
 
 function add_platform() {
-    if [[ -z ${__current_platform:-} ]] ; then
+    if [[ -z ${_____current_platform:-} ]] ; then
 	fatal "Attempt to add a platform outside of its definition"
     fi
     local -r dispatch=$1
+    local plat
     for plat in "${!global_platforms[@]}" ; do
-	if [[ $__current_platform = "$plat" ]] ; then return; fi
+	if [[ $_____current_platform = "$plat" ]] ; then return; fi
     done
-    global_platforms[$__current_platform]=$dispatch
+    global_platforms[$_____current_platform]=$dispatch
 }
 
 function __list_instance_types() {
@@ -1112,11 +1104,12 @@ function process_option() {
 }
 
 function register_options() {
-    if [[ -z ${__current_platform:-} ]] ; then
+    if [[ -z ${_____current_platform:-} ]] ; then
 	fatal "Attempt to register options outside of platform definition"
     fi
+    local opt
     for opt in "$@" ; do
-	option_registrations[$opt]=$__current_platform
+	option_registrations[$opt]=$_____current_platform
     done
 }
 
@@ -1178,24 +1171,62 @@ function process_extended_options() {
     done
 }
 
-if [[ -n ${OPENSHIFT_OINST_LIBDIR:-} ]] ; then
-    readarray -t platform_path <<< "${OPENSHIFT_OINST_LIBDIR//:/$'\n'}"
-fi
-platform_path+=("$___topdir")
-
-for dir in "${platform_path[@]}" ; do
-    dir=${dir:-.}
-    if [[ -d "$dir/share/OpenShift/installer/platforms" ]] ; then
-	for f in "$dir/share/OpenShift/installer/platforms"/* ; do
-	    __current_platform=${f##*/}
-	    if [[ -z ${global_platforms[$__current_platform]:-} && $f != "."* && $f != *"~" && $f != '#'* && -f $f ]] ; then
-		. "$f"
-	    fi
-	    unset __current_platform
-	done
+function find_platforms() {
+    local -a _____platform_path
+    local -a _____new_vars
+    local -A _____var_map
+    local _____a
+    local _____f
+    local _____dir
+    if [[ -n ${OPENSHIFT_OINST_LIBDIR:-} ]] ; then
+	readarray -t _____platform_path <<< "${OPENSHIFT_OINST_LIBDIR//:/$'\n'}"
     fi
-done
+    _____platform_path+=("$___topdir")
+    for _____dir in "${_____platform_path[@]}" ; do
+	_____dir=${_____dir:-.}
+	if [[ -d "$_____dir/share/OpenShift/installer/platforms" ]] ; then
+	    for _____f in "$_____dir/share/OpenShift/installer/platforms"/* ; do
+		local -i _____warned_platvar=0
+		_____current_platform=${_____f##*/}
+		if [[ -z ${global_platforms[$_____current_platform]:-} && $_____current_platform != "."* && $_____current_platform != *"~" && $_____current_platform != '#'* && -f $_____f ]] ; then
+		    _____new_vars=()
+		    _____var_map=()
+		    while read -r _____a ; do
+			_____var_map[$_____a]=1
+		    done <<< "$(compgen -v; compgen -c)"
+		    unset _____a
+		    # shellcheck disable=SC1090
+		    . "$_____f"
+		    readarray -t _____new_vars <<< "$(compgen -v; compgen -c)"
+		    for _____a in "${_____new_vars[@]}" ; do
+			if [[ -z ${_____var_map[$_____a]:-} &&
+				  $_____a != "_____$_____current_platform"* ]] ; then
+			    if ! ((_____warned_platvar)) ; then
+				echo "Unexpected variable/function names from $_____current_platform platform defined in"
+				echo "${_____f//\/\//\/}"
+				echo "Names should be prefixed with _____$_____current_platform"
+				_____warned_platvar=1
+			    fi
+			    echo "    $_____a"
+			fi
+		    done
+		fi
+		unset _____current_platform
+	    done
+	fi
+    done
+}
 
+# Running nested installs is liable to be problematic
+if [[ -n ${OPENSHIFT_INSTALL_INTERLOCK:-} ]] ; then
+    if [[ ${1:-} = -h* ]] ; then
+	echo "Already in ${___topsc:-oinst} environment!"
+	help
+    fi
+    fatal "Already in ${___topsc:-oinst} environment"
+fi
+
+find_platforms
 process_options "$@"
 clear_env
 if [[ -z ${install_type:-} ]] ; then
