Attempt to make the monitor more robust

diff --git a/bench-army-knife/tools/bench-army-knife-fio b/bench-army-knife/tools/bench-army-knife-fio
--- a/bench-army-knife/tools/bench-army-knife-fio
+++ b/bench-army-knife/tools/bench-army-knife-fio
@@ -19,6 +19,12 @@ function fatal() {
     exit 1
 }
 
+function debug() {
+    if (( debug )) ; then
+	echo "DEBUG: $*" 1>&2
+    fi
+}
+
 # Find our helpers
 function finddir() {
     local path_to_file
@@ -135,6 +141,7 @@ Usage: ${___topsc:-$0} [options] [-- pbench-${bm_name} args]
                       be generated if not provided.
        -C name        Use the specified name for the controller's hostname
        -c configname  Record the specified configuration name
+       -D 	      Enable debugging.
        -E             Don't use external agents on worker nodes.
                       Default with non-Kata pods
        -e             Use external agents on the worker nodes.
@@ -191,11 +198,12 @@ EOF
     exit 1
 }
 
-while getopts 'A:C:c:EeF:fHIi:J:Kk:L:M:m:N:nP:p:qR:r:SsTu:V:wXxYy' opt ; do
+while getopts 'A:C:c:DEeF:fHIi:J:Kk:L:M:m:N:nP:p:qR:r:SsTu:V:wXxYy' opt ; do
     case "$opt" in
 	A) pbench_agent_key=$OPTARG	 ;;
 	C) hostname=$OPTARG		 ;;
 	c) configname=$OPTARG		 ;;
+	D) debug=1			 ;;
 	E) force_external_agents=1	 ;;
 	e) force_external_agents=0	 ;;
 	F) additional_files+=("$OPTARG") ;;
@@ -2005,15 +2013,114 @@ function cleanup_report() {
     fi
 }
 
+function get_pod_uid() {
+    local pod=$1
+    local ns=${2:-}
+    local answer
+    answer=$(oc get pod ${ns:+-n "$ns"} "$pod" -ojson 2>/dev/null | jq -r .metadata.uid)
+    if [[ -n "$answer" ]] ; then
+	echo "$answer"
+	return 0
+    else
+	return 1
+    fi
+}
+
+function get_pod_phase() {
+    local pod=$1
+    local uid=$2
+    local ns=${3:-}
+    read -r answer_uid phase <<< "$(oc get pod ${ns:+-n "$ns"} "$pod" -ojson 2>/dev/null | jq -r '.metadata.uid + " " + .status.phase')"
+    if [[ $uid != "$answer_uid" ]] ; then
+	return 2
+    elif [[ -n "$phase" ]] ; then
+	echo "$phase"
+	return 0
+    else
+	return 1
+    fi
+}
+
 function monitor_reporting_1() {
     local tmp1
-    tmp1=$(mktemp "/tmp/bench-army-knife${bm_name:+-$bm_name}-resultsXXXXXX.json")
-    # TODO Need a better check here.
-    until oc rsh -T -n "$namespace" "${namespace}-controller" sh -c "while [[ ! -f '$report_file' ]] ; do sleep 5; done; cat '$report_file'" > "$tmp1"; do
+    local pod_uid=
+    local pod_phase=
+    while : ; do
+	pod_uid=$(get_pod_uid "${namespace}-controller" "$namespace")
+	[[ -n "$pod_uid" ]] && break
 	sleep 5
     done
-    # Don't clear the report file until we have it safely off the controller
-    oc rsh -T -n "$namespace" "${namespace}-controller" sh -c "rm -f '$report_file'"
+    debug ">>> Waiting for pod to start running"
+    while : ; do
+	pod_phase=$(get_pod_phase "${namespace}-controller" "$pod_uid" "$namespace")
+	case "$?" in
+	    2) fatal "Pod $namespace/${namespace}-controller is not the same pod it originally was!" ;;
+	    1) fatal "Cannot get status for pod $namespace/${namespace}-controller" ;;
+	    0)
+		debug " >> phase is ${pod_phase}"
+		case "${pod_phase,,}" in
+		    running) break ;;
+		    error) fatal "Pod $namespace/${namespace}-controller failed!" ;;
+		    *) debug "Waiting for pod $namespace/${namespace}-controller to run ($pod_phase)" ;;
+		esac
+		;;
+	    *) fatal "Unexpected status $? from pod phase check" ;;
+	esac
+	sleep 5
+    done
+
+    debug ">>> pod is running, waiting for payload retrieval"
+    tmp1=$(mktemp "/tmp/bench-army-knife${bm_name:+-$bm_name}-resultsXXXXXX.json")
+    # TODO Need a better check here.
+    while : ; do
+	pod_phase=$(get_pod_phase "${namespace}-controller" "$pod_uid" "$namespace")
+	case "$?" in
+	    2) fatal "Pod $namespace/${namespace}-controller is not the same pod it originally was!" ;;
+	    1) fatal "Cannot get status for pod $namespace/${namespace}-controller" ;;
+	    0)
+		debug " >> pod phase is $pod_phase"
+		if [[ ${pod_phase,,} = running ]] ; then
+		    # It's possible that the pod will go away between the probe and payload retrieval.
+		    # That's OK; this will fail, and the next time around we'll pick up that it failed.
+		    if oc rsh -T -n "$namespace" "${namespace}-controller" sh -c "cat '$report_file'" > "$tmp1" 2>/dev/null ; then
+			debug "  > found report file $report_file"
+			# I've seen a few cases where apparently this command succeeded, even though the file
+			# didn't really exist.  The scenario appears to be a connection reset in the retrieval
+			# command.  So wait a few seconds to make sure that this was real.
+			sleep 5
+			oc rsh -T -n "$namespace" "${namespace}-controller" test -f "$report_file" >/dev/null 2>&1 && break
+			# In that case, try again.
+			echo "*** Report file $report_file vanished unexpectedly!" 1>&2
+		    fi
+		    sleep 5
+		else
+		    fatal "Pod $namespace/${namespace}-controller died prematurely!"
+		fi
+		;;
+	    *) fatal "Unexpected status $? from pod phase check" ;;
+	esac
+    done
+    debug ">>> Have report file, waiting to clean up"
+    # At this point, we have the report file.  Clear it out and keep monitoring until the pod goes away.
+    while : ; do
+	# Keep trying to remove it unconditionally until the pod goes away.
+	# This is in case something on the pod somehow tries to recreate the report file
+	# and the controller then never sees it gone.
+	oc rsh -T -n "$namespace" "${namespace}-controller" sh -c "rm -f '$report_file'" 2>/dev/null
+	pod_phase=$(get_pod_phase "${namespace}-controller" "$pod_uid" "$namespace")
+	case "$?" in
+	    2) fatal "Pod $namespace/${namespace}-controller is not the same pod it originally was!" ;;
+	    1) fatal "Cannot get status for pod $namespace/${namespace}-controller" ;;
+	    0) if [[ ${pod_phase,,} = running ]] ; then
+		   debug " >> Still running"
+		   break
+	       fi
+	       debug " >> Pod no longer running, $pod_phase"
+	       ;;
+	    *) fatal "Unexpected status $? from pod phase check" ;;
+	esac
+	sleep 5
+    done
     cat "$tmp1"
     rm -f "$tmp1"
     return 0
@@ -2028,7 +2135,7 @@ function monitor_reporting() {
     # on trying to retrieve the underlying objects until monitoring is complete.
     # Otherwise we might not retrieve all of the objects, or we might get them
     # in an earlier state.
-    monitor_reporting_1 | cleanup_report > "$tmp"
+    monitor_reporting_1 </dev/null | cleanup_report > "$tmp"
     jq -c --slurpfile objects <(oc get all -A -l "bench-army-knife-id=$job_uuid" -o json) '{results: .results, api_objects: [$objects[].items?[] | { kind: .kind, name: .metadata.name, namespace: .metadata.namespace}]}' < "$tmp" 1>&3
     rm -f "$tmp"
 }
