Add option to take prometheus snapshot to test suite

diff --git a/CI/run-kata-perf-suite b/CI/run-kata-perf-suite
--- a/CI/run-kata-perf-suite
+++ b/CI/run-kata-perf-suite
@@ -62,6 +62,9 @@ declare basename=
 declare analyze_results=
 declare -i debugonly=0
 declare force_cleanup_timeout=
+declare -i take_prometheus_snapshot=0
+declare snapshot_date_format='+%Y_%m_%dT%H_%M_%S%z'
+declare prometheus_snapshot_start_ts=
 
 declare -a runtimeclasses=('' 'kata')
 
@@ -92,6 +95,42 @@ function report_results() {
 	local result
 	result="$(IFS=","; echo "${results[*]}")"
 	echo "${result//,/,$'\n'}"
+    fi
+}
+
+function retrieve_prometheus_timestamp() {
+    "${OC}" exec -n openshift-monitoring prometheus-k8s-0 -- /bin/sh -c "date  -- /bin/sh -c '+$snapshot_date_format'"
+}
+    
+function start_prometheus_snapshot() {
+    echo "Starting Prometheus snapshot" 1>&2
+    $(OC) delete pod -n openshift-monitoring prometheus-k8s-0
+    local -i retry=12
+    until $(OC) get pod -n openshift-monitoring prometheus-k8s-0 >/dev/null 2>&1 ; do
+	echo "Promtheus pod did not start, $retry attempt(s) left" 1>&2
+	((retry > 0)) || fatal "Prometheus pod did not restart!"
+	retry=$((retry-1))
+	sleep 5
+    done
+    "${OC}" wait --for=condition=Ready -n openshift-monitoring pod/prometheus-k8s-0 || fatal "Prometheus pod did not become ready"
+    # Wait for prometheus pod to fully initialize
+    sleep 60
+    prometheus_snapshot_start_ts=$(retrieve_prometheus_timestamp) || fatal "Unable to retrieve starting timestamp from Prometheus!"
+    echo "Prometheus snapshot started" 1>&2
+}
+
+function retrieve_prometheus_snapshot() {
+    [[ -n "$prometheus_snapshot_start_ts" ]] || return
+    echo "Retrieving Prometheus snapshot" 1>&2
+    sleep 60
+    local prometheus_snapshot_end_ts
+    prometheus_snapshot_end_ts=$(retrieve_prometheus_timestamp)
+    local promdb_name="promdb_${prometheus_snapshot_start_ts}_${prometheus_snapshot_end_ts}"
+    local promdb_path="${artifactdir:+${artifactdir}/}${promdb_name}.tar"
+    if "${OC}" exec -n openshift-monitoring prometheus-k8s-0 -c prometheus -- /bin/sh -c "tar cf - . -C /prometheus --transform 's,^[.],./${promdb_name},' .; true" > "$promdb_path" ; then
+	echo "Prometheus snapshot retrieved" 1>&2
+    else
+	echo "Unable to retrieve Prometheus snapshot" 1>&2
     fi
 }
 
@@ -147,6 +186,9 @@ function finis() {
 	    statusmsg=Failed
 	else
 	    status=PASS
+	fi
+	if [[ -n "$prometheus_snapshot_start_ts" ]] ; then
+	    retrieve_prometheus_snapshot
 	fi
 	echo "Run took $(to_hms "$starting_timestamp" "$ending_timestamp") ($statusmsg)"
 	starting_timestamp=
@@ -235,7 +277,7 @@ function set_pin_nodes() {
     if [[ -z "$client_pin_node" || -z "$server_pin_node" || -z "$sync_pin_node" ]] ; then
 	local -a nodes
 	# shellcheck disable=SC2207
-	nodes=($(${OC} get node -l node-role.kubernetes.io/worker= -o jsonpath='{.items[*].metadata.name}'))
+	nodes=($("${OC}" get node -l node-role.kubernetes.io/worker= -o jsonpath='{.items[*].metadata.name}'))
 	local -i node_count=${#nodes[@]}
 	if ((node_count < 1)) ; then
 	    finis "No nodes found!"
@@ -255,7 +297,7 @@ function set_pin_nodes() {
 function get_node_memory() {
     local node=$1
     local mem
-    mem=$(oc get node "$node" -ojsonpath='{.status.allocatable.memory}')
+    mem=$("${OC}" get node "$node" -ojsonpath='{.status.allocatable.memory}')
     parse_size "$mem"
 }
 
@@ -291,11 +333,11 @@ function process_profile() {
 }
 
 function force_pull_base_image() {
-    for n in $(oc get node --no-headers |awk '{print $1}') ; do
+    for n in $("${OC}" get node --no-headers |awk '{print $1}') ; do
 	if ((debugonly)) ; then
-	    echo oc debug --no-stdin=true --no-tty=true node/"$n" -- chroot /host sh -c ' podman pull quay.io/rkrawitz/bench-army-base; podman pull quay.io/rkrawitz/bench-army-base'
+	    echo "${OC}" debug --no-stdin=true --no-tty=true node/"$n" -- chroot /host sh -c ' podman pull quay.io/rkrawitz/bench-army-base; podman pull quay.io/rkrawitz/bench-army-base'
 	else
-	    oc debug --no-stdin=true --no-tty=true node/"$n" -- chroot /host sh -c ' podman pull quay.io/rkrawitz/bench-army-base; podman pull quay.io/rkrawitz/bench-army-base' &
+	    "${OC}" debug --no-stdin=true --no-tty=true node/"$n" -- chroot /host sh -c ' podman pull quay.io/rkrawitz/bench-army-base; podman pull quay.io/rkrawitz/bench-army-base' &
 	fi
     done
     if ((! debugonly)) ; then
@@ -375,7 +417,10 @@ $(_document_workloads)
                                 Known profiles:
 $(list_profiles '                                - ')
         --uuid=uuid             Specify a uuid for the job run.  Default is to
-				generate one.
+                                generate one.
+        --prometheus-snapshot
+                                Take a Prometheus snapshot and save to the
+                                artifacts directory
 
     Virtiofsd configuration options (for kata):
         --virtiofsd-direct      Allow direct I/O requests from guest to operate
@@ -443,6 +488,7 @@ function process_option() {
 	basename) basename=$optvalue							;;
 	uuid) uuid=$optvalue								;;
 	forcecleanupiknowthisisdangerous) force_cleanup_timeout=$optvalue		;;
+	prometheussnapshot) take_prometheus_snapshot=$(bool "$optvalue")		;;
 
 	virtiofsdwriteback) virtiofsd_writeback=$(bool "$optvalue")			;;
 	virtiofsddirect) virtiofsd_direct=$(bool "$optvalue")				;;
@@ -661,6 +707,9 @@ fi
 
 if ((! debugonly)) ; then
     set_pin_nodes
+    if ((take_prometheus_snapshot)) ; then
+	start_prometheus_snapshot
+    fi
     starting_timestamp=$(date +%s)
     job_datestamp=$(date -u '+%Y_%m_%dT%H_%M_%S%z' --date=@"$starting_timestamp")
     artifactdir=${artifactdir//%s/$job_datestamp}
