- Add analyzer for cluserbuster-report - Add more fio options - Fix removal of temp file when polling logs

diff --git a/CI/run-kata-perf-suite b/CI/run-kata-perf-suite
--- a/CI/run-kata-perf-suite
+++ b/CI/run-kata-perf-suite
@@ -26,11 +26,13 @@ declare server_pin_node=
 declare sync_pin_node=
 declare -i job_runtime=60
 declare -i job_timeout=-1200
-declare artifactdir='/tmp/logz/%s-%n'
+declare artifactdir=
 declare report_format=parseable-summary
+declare -i report_object_creation=0
+declare -i cleanup=0
 
 declare -a workloads=(scaling uperf fio)
-declare -a runtimeclasses=('' '--kata')
+declare -a runtimeclasses=('' 'kata')
 
 declare -i scaling_starting_namespaces=1
 declare -i scaling_deps_per_namespace=5
@@ -44,16 +46,16 @@ declare -a uperf_test_types=(stream rr)
 declare -i uperf_job_runtime=0
 declare -i uperf_job_timeout=0
 
-declare -a fio_engines=(sync libaio)
-declare -a fio_ninst=(1 4)
 declare -a fio_blocksizes=(4096 1048576)
 declare -a fio_patterns=(read write randread randwrite)
+declare -a fio_directs=(0)
+declare -a fio_fdatasyncs=(0)
+declare -a fio_iodepths=(1)
+declare -a fio_ioengines=(sync libaio)
+declare -a fio_ninst=(1 4)
 declare -i fio_job_runtime=0
 declare fio_workdir=/var/tmp
 declare -i fio_filesize=
-declare -i fio_fdatasync=1
-declare -i fio_direct=0
-declare -i fio_io_depth=1
 declare -i fio_ramptime=5
 declare -i fio_job_timeout=-3600
 declare -i fio_pod_memsize=
@@ -61,11 +63,13 @@ declare -i fio_pod_memsize=
 declare -i fail=0
 declare -i counter=0
 declare -i hard_fail_on_error=0
+declare -i restart=0
 
 declare -a failures=()
 declare -a jobs=()
 declare -A job_runtimes=()
 
+declare starting_timestamp=
 declare job_datestamp
 
 function finis() {
@@ -98,11 +102,13 @@ function fatal() {
 }
 
 function bool() {
-    local value=${1:-}
-    case "${value,,}" in
-	''|1|y|yes|tru*) echo 1 ;;
-	*)               echo 0 ;;
-    esac
+    local value
+    for value in "$@" ; do
+	case "${value,,}" in
+	    ''|1|y|yes|tru*) echo 1 ;;
+	    *)               echo 0 ;;
+	esac
+    done
 }
 
 function parse_size() {
@@ -165,6 +171,7 @@ function splitarg() {
 function set_pin_nodes() {
     if [[ -z "$client_pin_node" || -z "$server_pin_node" || -z "$sync_pin_node" ]] ; then
 	local -a nodes
+	# shellcheck disable=SC2207
 	nodes=($(${OC} get node -l node-role.kubernetes.io/worker= -o jsonpath='{.items[*].metadata.name}'))
 	local -i node_count=${#nodes[@]}
 	[[ -z "$client_pin_node" ]] && client_pin_node=${nodes[$((0 % node_count))]}
@@ -187,42 +194,44 @@ function process_option() {
     read -r noptname1 noptname optvalue <<< "$(parse_option "$1")"
     optvalue=$(splitarg "$optvalue")
     case "$noptname1" in
-	clientpin*) client_pin_node=$optvalue				;;
-	serverpin*) server_pin_node=$optvalue				;;
-	syncpin*) sync_pin_node=$optvalue				;;
-	jobruntime|runtime) job_runtime=$optvalue			;;
-	jobtimeout|timeout) job_timeout=$optvalue			;;
-	artifact*) artifactdir=$optvalue				;;
-	report*) report_format=$optvalue				;;
-	runtimeclass*) readarray -t runtimeclasses <<< "$optvalue"	;;
+	clientpin*) client_pin_node=$optvalue					;;
+	serverpin*) server_pin_node=$optvalue					;;
+	syncpin*) sync_pin_node=$optvalue					;;
+	jobruntime|runtime) job_runtime=$optvalue				;;
+	jobtimeout|timeout) job_timeout=$optvalue				;;
+	artifactdir) artifactdir=$optvalue					;;
+	reportformat*) report_format=$optvalue					;;
+	runtimeclass*) readarray -t runtimeclasses <<< "$optvalue"		;;
+	reportobject*) report_object_creation=$(bool "$optvalue")		;;
+	cleanup*) cleanup=$(bool "$optvalue")					;;
 
-	scalingstarting*) scaling_starting_namespaces=$optvalue		;;
-	scalingdeps*) scaling_deps_per_namespace=$optvalue		;;
-	scaling*runtime) scaling_job_runtime=$optvalue			;;
-	scaling*timeout) scaling_job_timeout=$optvalue			;;
+	scalingstarting*) scaling_starting_namespaces=$optvalue			;;
+	scalingdeps*) scaling_deps_per_namespace=$optvalue			;;
+	scaling*runtime) scaling_job_runtime=$optvalue				;;
+	scaling*timeout) scaling_job_timeout=$optvalue				;;
 
-	uperfmsg*) readarray -t uperf_msg_sizes <<< "$optvalue"		;;
-	uperfnthr*) readarray -t uperf_nthrs <<< "$optvalue"		;;
-	uperfninst*) readarray -t uperf_ninst <<< "$optvalue"		;;
-	uperftest*) readarray -t uperf_test_types <<< "$optvalue"	;;
-	uperf*runtime) uperf_job_runtime=$optvalue			;;
-	uperf*timeout) uperf_job_timeout=$optvalue			;;
+	uperfmsg*) readarray -t uperf_msg_sizes <<< "$optvalue"			;;
+	uperfnthr*) readarray -t uperf_nthrs <<< "$optvalue"			;;
+	uperfninst*) readarray -t uperf_ninst <<< "$optvalue"			;;
+	uperftest*) readarray -t uperf_test_types <<< "$optvalue"		;;
+	uperf*runtime) uperf_job_runtime=$optvalue				;;
+	uperf*timeout) uperf_job_timeout=$optvalue				;;
 
-	fioeng*) readarray -t fio_engines <<< "$optvalue"		;;
-	fioninst*) readarray -t fio_ninst <<< "$optvalue"		;;
-	fioblock*) readarray -t fio_blocksizes <<< "$optvalue"		;;
-	fiopat*) readarray -t fio_patterns <<< "$optvalue"		;;
-	fioworkdir) fio_workdir=$optvalue				;;
-	fio*runtime) fio_job_runtime=$optvalue				;;
-	fioiodepth) fio_io_depth=$optvalue				;;
-	fiofdatasync) fio_fdatasync=$(bool "$optvalue")			;;
-	fiodirect) fio_direct=$(bool "$optvalue")			;;
-	fioramp*) fio_ramptime=$optvalue				;;
-	fiofilesize) fio_filesize=$(parse_size "$optvalue")		;;
-	fio*timeout) fio_job_timeout=$optvalue				;;
-	fio*memsize) fio_pod_memsize=$(parse_size "$optvalue")		;;
+	fioblock*) readarray -t fio_blocksizes <<< "$optvalue"			;;
+	fiopat*) readarray -t fio_patterns <<< "$optvalue"			;;
+	fiodirect*) readarray -t fio_directs <<< "$(bool "$optvalue")"		;;
+	fiofdatasync*) readarray -t fio_fdatasyncs <<< "$(bool "$optvalue")"	;;
+	fioiodepth*) readarray -t fio_iodepths <<< "$optvalue"			;;
+	fioioeng*) readarray -t fio_ioengines <<< "$optvalue"			;;
+	fioninst*) readarray -t fio_ninst <<< "$optvalue"			;;
+	fioworkdir) fio_workdir=$optvalue					;;
+	fio*runtime) fio_job_runtime=$optvalue					;;
+	fioramp*) fio_ramptime=$optvalue					;;
+	fiofilesize) fio_filesize=$(parse_size "$optvalue")			;;
+	fio*timeout) fio_job_timeout=$optvalue					;;
+	fio*memsize) fio_pod_memsize=$(parse_size "$optvalue")			;;
 
-	*) fatal "Unknown option --$1"					;;
+	*) fatal "Unknown option --$1"						;;
     esac
 }
 
@@ -272,63 +281,107 @@ function to_hms() {
 
 function xruntimeclass() {
     local runtimeclass=$1
-    if [[ $runtimeclass == --kata ]] ; then
+    if [[ $runtimeclass == kata ]] ; then
 	echo kata
     else
 	echo nonkata
     fi
 }
 
-function run_cb() {
+function doit() {
+    echo "$*"
+    "$@"
+}
+
+function run_clusterbuster() {
     local OPTIND=0
     local opt
     local -i error_is_failure=1
-    while getopts 'yn' opt "$@" ; do
+    local jobdir=
+    local tmp_jobdir=
+    local jobname=
+    local runtimeclass=
+    local workload=
+    local timeout=
+    while getopts 'ynj:r:w:t:' opt "$@" ; do
 	case "$opt" in
-	    y) error_is_failure=0 ;;
-	    n) error_is_failure=1 ;;
-	    *)                    ;;
+	    y) error_is_failure=0	;;
+	    n) error_is_failure=1	;;
+	    j) jobname="$OPTARG"	;;
+	    r) runtimeclass="$OPTARG"	;;
+	    w) workload="$OPTARG"	;;
+	    t) timeout="$OPTARG"	;;
+	    *)				;;
 	esac
     done
+    [[ -z "$jobname" ]] && fatal "Job name must be specified"
+    [[ -z "$workload" ]] && fatal "Workload must be specified"
+    jobname=$(printf '%s-%s-%04d-%s' "$workload" "$(xruntimeclass "$runtimeclass")" "$counter" "$jobname")
+    jobdir=${artifactdir:+$artifactdir/$jobname}
+    counter=$((counter+1))
+    if [[ -n "$jobdir" && -d "$jobdir" ]] ; then
+	if ((restart)) ; then
+	    echo "$jobname is already present"
+	    return 0
+	else
+	    rm -rf "$jobdir"
+	fi
+    fi
+    tmp_jobdir="${jobdir:+${jobdir}.tmp}"
     shift $((OPTIND-1))
-    local jobname="$1"; shift
     local -i status=0
-    echo "clusterbuster " "--jobname=$jobname" "$@"
     local -i job_start
     local -i job_end
     job_start=$(date +%s)
-    clusterbuster "--jobname=$jobname" "$@" || status=1
+    echo
+    echo "*** Running $jobname"
+    doit "clusterbuster" \
+	 --precleanup --cleanup="$cleanup" --image-pull-policy=IfNotPresent --drop-cache \
+	 --metrics --report="$report_format" --workload="$workload" \
+	 ${job_runtime:+"--workload_runtime=$job_runtime"} \
+	 ${client_pin_node:+"--pin-node=client=$client_pin_node"} \
+	 ${server_pin_node:+"--pin-node=server=$server_pin_node"} \
+	 ${sync_pin_node:+"--pin-node=sync=$sync_pin_node"} \
+	 ${timeout:+"--timeout=$timeout"} \
+	 ${jobname:+"--jobname=$jobname"} \
+	 ${tmp_jobdir:+"--artifactdir=$tmp_jobdir"} \
+	 ${runtimeclass:+"--runtimeclass=$runtimeclass"} \
+	 --report_object_creation="$report_object_creation" \
+	 "$@" || status=1
     job_end=$(date +%s)
-    ((status == 0)) && jobs+=("$jobname")
     job_runtimes[$jobname]="$(to_hms "$job_start" "$job_end")"
-    if ((status != 0)) ; then
+    if ((status == 0)) ; then
+	jobs+=("$jobname")
+	if [[ -n "$jobdir" ]] ; then
+	    [[ -d "$jobdir" ]] && fatal "$jobdir exists (shouldn't!)"
+	    mv "$tmp_jobdir" "$jobdir" || fatal "Can't rename $tmp_jobdir to $jobdir"
+	fi
+    else
 	((error_is_failure)) && failures+=("$jobname")
+	if [[ -n "$jobdir" ]] ; then
+	    local fail_jobdir_base="${jobdir}.FAIL"
+	    local fail_jobdir=$fail_jobdir_base
+	    local -i jobdir_idx=1
+	    while [[ -d "$fail_jobdir" ]] ; do
+		fail_jobdir="${fail_jobdir_base}.$jobdir_idx"
+		jobdir_idx=$((jobdir_idx+1))
+	    done
+	    mv "$tmp_jobdir" "$fail_jobdir" || fatal "Can't rename $tmp_jobdir to $fail_jobdir"
+	fi
 	((hard_fail_on_error)) && finis
     fi
     return $status
-}
-
-function get_counter() {
-    printf '%04d' $counter
 }
 
 function test_scaling() {
     local runtimeclass=$1
     namespaces=$scaling_starting_namespaces
     while :; do
-	echo
-	job_name="$(get_counter)-podscale-$(xruntimeclass "$runtimeclass")-$((namespaces*scaling_deps_per_namespace))"
-	counter=$((counter+1))
+	job_name="$((namespaces*scaling_deps_per_namespace))"
 	echo "*** Running $((namespaces * scaling_deps_per_namespace)) pods"
-	if run_cb -y "$job_name" --workload=cpusoaker --deployments="$scaling_deps_per_namespace" \
-		  --namespaces="$namespaces" --workload-runtime="$job_runtime" \
-		  --objs_per_call=6 --parallel=100 --precleanup --no-cleanup \
-		  ${artifactdir:+"--artifactdir=$artifactdir"} \
-		  --image-pull-policy=IfNotPresent --drop-cache \
-		  ${client_pin_node:+"--pin-node=client=$client_pin_node"} \
-		  ${sync_pin_node:+"--pin-node=sync=$sync_pin_node"} \
-		  --metrics --report="$report_format" --no-report-object-creation \
-		  ${runtimeclass:+"$runtimeclass"} --timeout="$scaling_job_timeout" ; then
+	if run_clusterbuster -y -j "$job_name" -w cpusoaker -r "$runtimeclass" -t "$scaling_job_timeout" -- \
+			     --deployments="$scaling_deps_per_namespace" \
+			     --namespaces="$namespaces" --objs_per_call=6 --parallel=100 ; then
 	    namespaces=$((namespaces+1))
 	else
 	    echo "Run failed: $?"
@@ -348,22 +401,13 @@ function test_uperf() {
 	for nthr in "${uperf_nthrs[@]}" ; do
 	    for ninst in "${uperf_ninst[@]}" ; do
 		for test_type in "${uperf_test_types[@]}" ; do
-		    job_name="$(get_counter)-uperf-$(xruntimeclass "$runtimeclass")-${msg_size}B-${nthr}i-${ninst}P-${test_type}"
-		    counter=$((counter+1))
-		    run_cb "$job_name" --workload=uperf --workload_runtime="$job_runtime" \
-			   --uperf_msg_size="$msg_size" \
-			   --uperf_test_type="$test_type" \
-			   --uperf_proto=tcp \
-			   --uperf_nthr="$nthr" \
-			   --pod-annotation="io.katacontainers.config.hypervisor.default_vcpus: \"$nthr\"" \
-			   --precleanup --no-cleanup \
-			   ${artifactdir:+"--artifactdir=$artifactdir"} \
-			   --image-pull-policy=IfNotPresent --drop-cache \
-			   ${client_pin_node:+"--pin-node=client=$client_pin_node"} \
-			   ${server_pin_node:+"--pin-node=server=$server_pin_node"} \
-			   ${sync_pin_node:+"--pin-node=sync=$sync_pin_node"} \
-			   --metrics --report="$report_format" --no-report-object-creation \
-			   ${runtimeclass:+"$runtimeclass"} --timeout="$uperf_job_timeout"
+		    job_name="${msg_size}B-${nthr}i-${ninst}P-${test_type}"
+		    run_clusterbuster -j "$job_name" -w uperf -r "$runtimeclass" -t "$uperf_job_timeout" -- \
+				      --uperf_msg_size="$msg_size" \
+				      --uperf_test_type="$test_type" \
+				      --uperf_proto=tcp \
+				      --uperf_nthr="$nthr" \
+				      --pod-annotation="io.katacontainers.config.hypervisor.default_vcpus: \"$nthr\""
 		done
 	    done
 	done
@@ -373,39 +417,29 @@ function test_uperf() {
 function test_fio() {
     local runtimeclass=$1
     local -i ninst
-    local engine
     local memory_annotation=
     if ((fio_pod_memsize > 0)) ; then
+	# shellcheck disable=SC2089
 	memory_annotation=--pod-annotation="io.katacontainers.config.hypervisor.default_memory: \"$fio_pod_memsize\""
     fi
     for ninst in "${fio_ninst[@]}" ; do
 	local filesize=$((fio_filesize / ninst))
-	for engine in "${fio_engines[@]}" ; do
-	    job_name="$(get_counter)-fio-$(xruntimeclass "$runtimeclass")-$(IFS=,; echo "${fio_blocksizes[*]}")Bi-${ninst}P-${engine}"
-	    counter=$((counter+1))
-	    run_cb "$job_name" --workload=fio --workload_runtime="$job_runtime" \
-		   --fio-blocksize="$(IFS=,; echo "${fio_blocksizes[*]}")" \
-		   --fio-patterns="$(IFS=,; echo "${fio_patterns[*]}")" \
-		   --fio-ioengine="$engine" \
-		   --fio_filesize="$filesize" \
-		   --fio_ramp_time="$fio_ramptime" \
-		   --fio_iodepth="$fio_io_depth" \
-		   --fio_direct="$fio_direct" \
-		   --fio_fdatasync="$fio_fdatasync" \
-		   --fio_workdir="$fio_workdir" \
-		   ${memory_annotation:+"$memory_annotation"} \
-		   --precleanup --no-cleanup \
-		   ${artifactdir:+"--artifactdir=$artifactdir"} \
-		   --image-pull-policy=IfNotPresent --drop-cache \
-		   ${client_pin_node:+"--pin-node=client=$client_pin_node"} \
-		   ${sync_pin_node:+"--pin-node=sync=$sync_pin_node"} \
-		   --metrics --report="$report_format" --no-report-object-creation \
-		   ${runtimeclass:+"$runtimeclass"} --timeout="$fio_job_timeout"
-	done
+	job_name="fio-${ninst}P"
+	# shellcheck disable=SC2090
+	run_clusterbuster -j "$job_name" -w fio -r "$runtimeclass" -t "$fio_job_timeout" -- \
+			  --fio-blocksize="$(IFS=,; echo "${fio_blocksizes[*]}")" \
+			  --fio-patterns="$(IFS=,; echo "${fio_patterns[*]}")" \
+			  --fio-ioengines="$(IFS=,; echo "${fio_ioengines[*]}")" \
+			  --fio-iodepths="$(IFS=,; echo "${fio_iodepths[*]}")" \
+			  --fio-fdatasyncs="$(IFS=,; echo "${fio_fdatasyncs[*]}")" \
+			  --fio-directs="$(IFS=,; echo "${fio_directs[*]}")" \
+			  --fio_filesize="$filesize" \
+			  --fio_ramp_time="$fio_ramptime" \
+			  --fio_workdir="$fio_workdir" \
+			  ${memory_annotation:+"$memory_annotation"}
     done
 }
 
-declare starting_timestamp
 starting_timestamp=$(date +%s)
 job_datestamp=$(date -u '+%Y_%m_%dT%H_%M_%S%z' --date=@"$starting_timestamp")
 artifactdir=${artifactdir//%s/$job_datestamp}
@@ -413,6 +447,8 @@ trap 'fail=2; finis' TERM HUP INT EXIT
 
 for runtimeclass in "${runtimeclasses[@]}" ; do
     for workload in "${workloads[@]}" ; do
+	# Use a separate counter for each workload/runtime
+	counter=0
 	case "$workload" in
 	    scal*) test_scaling "$runtimeclass" ;;
 	    uperf) test_uperf "$runtimeclass" ;;
diff --git a/clusterbuster b/clusterbuster
--- a/clusterbuster
+++ b/clusterbuster
@@ -646,11 +646,13 @@ function parse_volume_spec() {
 }
 
 function bool() {
-    local value=${1:-}
-    case "${value,,}" in
-	''|1|y|yes|tru*) echo 1 ;;
-	*)               echo 0 ;;
-    esac
+    local value
+    for value in "$@" ; do
+	case "${value,,}" in
+	    ''|1|y|yes|tru*) echo 1 ;;
+	    *)               echo 0 ;;
+	esac
+    done
 }
 
 function parse_option() {
@@ -1356,7 +1358,7 @@ function _get_logs_poll() {
 function get_logs_poll() {
     local tfile
     tfile=$(mktemp -p "$cb_tempdir" -t '_clusterbusterlogs.XXXXXXXXXX') || fatal "Cannot create temporary file"
-    trap 'rm -f "$tfile"; echo "Status: Fail"; return 1' INT TERM HUP USR1
+    trap "rm -f '$tfile'; echo 'Status: Fail'; return 1" INT TERM HUP USR1
     _get_logs_poll "$@" > "$tfile"
     local status=$?
     if ((status == 0)) ; then
